### ISSUE TITLE
Doomer Wave 1.5 TODO 

### ISSUE THREAD

**Issue by stakanyash** [ksh1vn/DoomerWave#10]
### Community Remaster 1.15 (Doomer Wave 1.5):
- [ ] Adaptation for Improved Storyline
- [ ] Make cars skins black & white
- [ ] Rework rain weather effects
- [ ] Normalize volumes of all voicelines and music
- [ ] Transfer all text edits from ComRemaster
- [ ] Make b/w buttons in `data/if/frames/btngray1 (_hd for ComRem)`
